package eu.lschreiber.laminateapi.event;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a mixin method as an event-injection bridge.
 *
 * <p>The annotation processor generates a companion Mixin class that injects
 * at the specified point and fires the given Bukkit event. All generated
 * companion classes are automatically collected into a Mixin JSON
 * configuration file named {@code mixins.<plugin>.generated.json}, where
 * {@code <plugin>} is derived from the mixin package (e.g.
 * {@code eu.lschreiber.testplugin.mixins} →
 * {@code mixins.testplugin.generated.json}).</p>
 *
 * <p>The developer must add this filename to {@code plugin.yml} once:</p>
 * <pre>
 * mixins:
 *   - mixins.myplugin.json                # hand-written mixins
 *   - mixins.myplugin.generated.json      # auto-generated by @InjectEvent
 * </pre>
 *
 * <h3>Usage — string shorthand</h3>
 * <pre>{@code
 * @InjectEvent(
 *     method = "tick",          // simple name, or full JVM descriptor
 *     at     = At.HEAD,
 *     event  = ServerLevelTickStartEvent.class
 * )
 * private void onTick(BooleanSupplier hasTime) {}
 * }</pre>
 *
 * <h3>Usage — full {@link Rewrite} descriptor</h3>
 * <pre>{@code
 * @InjectEvent(
 *     methodRewrite = @Rewrite(method = "tick", args = BooleanSupplier.class),
 *     at      = At.HEAD,
 *     event   = ServerLevelTickStartEvent.class
 * )
 * private void onTick(BooleanSupplier hasTime) {}
 * }</pre>
 *
 * <p>Exactly one of {@link #method()} and {@link #methodRewrite()} must be set.
 * Setting both or neither is a compile-time error.</p>
 *
 * <p>The event class must have a constructor that accepts the Mixin target
 * instance followed by the marker method's parameters.</p>
 */
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.CLASS)
public @interface InjectEvent {

    /**
     * String shorthand for the target NMS method.
     *
     * <p>Accepted formats:</p>
     * <ul>
     *   <li>Simple name — {@code "tick"} — Mixin matches any overload with that name.</li>
     *   <li>Full JVM descriptor — {@code "tick(Ljava/util/function/BooleanSupplier;)V"} —
     *       unambiguously targets one specific overload.</li>
     * </ul>
     *
     * <p>Mutually exclusive with {@link #methodRewrite()}; exactly one must be set.</p>
     */
    String method() default "";

    /**
     * Full type-safe descriptor for the target NMS method.
     * The processor converts the {@link Rewrite} annotation into the JVM
     * descriptor that Mixin expects.
     *
     * <p>Mutually exclusive with {@link #method()}; exactly one must be set.</p>
     */
    Rewrite methodRewrite() default @Rewrite(method = "");

    /** Injection point within the target method. */
    At at();

    /** Bukkit event class to instantiate and fire. */
    Class<?> event();

    /**
     * Whether the injection may cancel the target method.
     * When {@code true} the generated code checks {@code event.isCancelled()}
     * and calls {@code CallbackInfo#cancel()} if cancelled. The event must
     * implement {@code Cancellable}.
     */
    boolean cancellable() default false;

    /**
     * JVM-format call-site descriptor for {@link At#INVOKE} injections.
     *
     * <p>Example: {@code "Lnet/minecraft/server/level/ServerChunkCache;tick(Ljava/util/function/BooleanSupplier;)V"}</p>
     *
     * <p>Ignored for {@link At#HEAD}, {@link At#TAIL}, and {@link At#RETURN}.</p>
     */
    String target() default "";
}
