package eu.lschreiber.laminateapi.accessor;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Runtime support for accessor interfaces generated by
 * {@link GenerateAccessorProcessor}.
 *
 * <p>Generated {@code of(Object)} factory methods delegate here to obtain a
 * {@link Proxy}-backed instance of the accessor interface, with
 * {@link MethodHandle} lookups cached per target class to avoid repeated
 * reflection overhead.</p>
 *
 * <p>This class is part of the public API because generated code references
 * it directly.</p>
 */
public final class LaminateAccessors {

    /** Cache: target class → (method descriptor → MethodHandle). */
    private static final ConcurrentHashMap<Class<?>, ConcurrentHashMap<String, MethodHandle>> CACHE =
            new ConcurrentHashMap<>();

    private LaminateAccessors() {
    }

    /**
     * Creates a proxy implementing {@code accessorInterface} that delegates
     * each method call to the corresponding mixin-injected method on
     * {@code target}.
     *
     * @param accessorInterface the generated accessor interface
     * @param target            the mixin-injected object (e.g. a MinecraftServer instance)
     * @param methodMappings    flat array of {@code [accessorName, mixinName, …]} pairs
     * @param <T>               accessor interface type
     * @return a proxy implementing {@code accessorInterface}
     * @throws IllegalArgumentException if {@code methodMappings} has an odd length
     * @throws NullPointerException     if any argument is {@code null}
     */
    @SuppressWarnings("unchecked")
    public static <T> T create(final Class<T> accessorInterface,
                               final Object target,
                               final String[] methodMappings) {
        Objects.requireNonNull(accessorInterface, "accessorInterface");
        Objects.requireNonNull(target, "target");
        Objects.requireNonNull(methodMappings, "methodMappings");

        if (methodMappings.length % 2 != 0) {
            throw new IllegalArgumentException(
                    "methodMappings must contain an even number of entries");
        }

        final Map<String, String> nameMap = buildNameMap(methodMappings);
        final Class<?> targetClass = target.getClass();
        final ConcurrentHashMap<String, MethodHandle> classHandles =
                CACHE.computeIfAbsent(targetClass, cls -> new ConcurrentHashMap<>());

        populateHandles(accessorInterface, targetClass, nameMap, classHandles);

        return (T) Proxy.newProxyInstance(
                accessorInterface.getClassLoader(),
                new Class<?>[]{accessorInterface},
                new AccessorInvocationHandler(target, targetClass, nameMap, classHandles));
    }

    // ── Setup helpers ───────────────────────────────────────────────────────

    private static Map<String, String> buildNameMap(final String[] methodMappings) {
        final Map<String, String> nameMap = new HashMap<>();
        for (int i = 0; i < methodMappings.length; i += 2) {
            nameMap.put(methodMappings[i], methodMappings[i + 1]);
        }
        return Map.copyOf(nameMap);
    }

    /**
     * Pre-resolves method handles for all interface methods so that the proxy's
     * invocation handler never encounters a cold lookup at call-time.
     */
    private static void populateHandles(final Class<?> accessorInterface,
                                        final Class<?> targetClass,
                                        final Map<String, String> nameMap,
                                        final ConcurrentHashMap<String, MethodHandle> classHandles) {
        final MethodHandles.Lookup lookup = obtainLookup(targetClass);

        for (final Method ifaceMethod : accessorInterface.getMethods()) {
            final String mixinName = nameMap.get(ifaceMethod.getName());
            if (mixinName == null) {
                continue;
            }

            final Class<?>[] paramTypes = ifaceMethod.getParameterTypes();
            final String desc = descriptor(mixinName, paramTypes);
            classHandles.computeIfAbsent(desc,
                    d -> resolveHandle(targetClass, mixinName, paramTypes, lookup));
        }
    }

    // ── Invocation handler ──────────────────────────────────────────────────

    /**
     * {@link java.lang.reflect.InvocationHandler} that routes proxy calls to
     * either {@code Object} methods (toString/hashCode/equals) or cached
     * mixin method handles.
     */
    private record AccessorInvocationHandler(
            Object target,
            Class<?> targetClass,
            Map<String, String> nameMap,
            ConcurrentHashMap<String, MethodHandle> classHandles
    ) implements java.lang.reflect.InvocationHandler {

        @Override
        public Object invoke(final Object proxy,
                             final Method method,
                             final Object[] args) throws Throwable {
            if (method.getDeclaringClass() == Object.class) {
                return handleObjectMethod(proxy, method, args);
            }
            return invokeMixinMethod(method, args);
        }

        private Object handleObjectMethod(final Object proxy,
                                          final Method method,
                                          final Object[] args) {
            return switch (method.getName()) {
                case "toString"  -> "LaminateAccessorProxy[" + target + "]";
                case "hashCode"  -> System.identityHashCode(proxy);
                case "equals"    -> proxy == firstArgOrNull(args);
                default          -> throw new UnsupportedOperationException(
                        "Unsupported Object method: " + method.getName());
            };
        }

        private Object invokeMixinMethod(final Method method,
                                         final Object[] args) throws Throwable {
            final String mixinName = nameMap.get(method.getName());
            if (mixinName == null) {
                throw new UnsupportedOperationException(
                        "No mixin mapping for accessor method: " + method.getName());
            }

            final String desc = descriptor(mixinName, method.getParameterTypes());
            final MethodHandle handle = classHandles.get(desc);
            if (handle == null) {
                throw new IllegalStateException(
                        "Mixin method '" + desc + "' not found on " + targetClass.getName()
                                + ". Ensure the hybrid plugin is loaded and the mixin is active.");
            }

            return handle.invokeWithArguments(prependTarget(target, args));
        }
    }

    // ── Reflection utilities ────────────────────────────────────────────────

    /**
     * Builds a descriptor key for caching: {@code "methodName(type1,type2)"}.
     */
    private static String descriptor(final String mixinName, final Class<?>[] paramTypes) {
        if (paramTypes.length == 0) {
            return mixinName + "()";
        }
        final StringBuilder sb = new StringBuilder(mixinName).append('(');
        for (int i = 0; i < paramTypes.length; i++) {
            if (i > 0) {
                sb.append(',');
            }
            sb.append(paramTypes[i].getName());
        }
        return sb.append(')').toString();
    }

    /**
     * Obtains a {@link MethodHandles.Lookup} with the widest access to the
     * target class. Falls back to the default lookup if private access is denied.
     */
    private static MethodHandles.Lookup obtainLookup(final Class<?> targetClass) {
        try {
            return MethodHandles.privateLookupIn(targetClass, MethodHandles.lookup());
        } catch (final IllegalAccessException e) {
            return MethodHandles.lookup();
        }
    }

    /**
     * Searches the target class hierarchy for a method matching the given name
     * and parameter types, returning an unreflected {@link MethodHandle}.
     *
     * @return the resolved handle, or {@code null} if no match was found
     */
    private static MethodHandle resolveHandle(final Class<?> targetClass,
                                              final String mixinName,
                                              final Class<?>[] paramTypes,
                                              final MethodHandles.Lookup lookup) {
        for (Class<?> cls = targetClass; cls != null; cls = cls.getSuperclass()) {
            for (final Method method : cls.getDeclaredMethods()) {
                if (method.getName().equals(mixinName)
                        && Arrays.equals(method.getParameterTypes(), paramTypes)) {
                    return unreflect(method, mixinName, lookup);
                }
            }
        }
        return null;
    }

    private static MethodHandle unreflect(final Method method,
                                          final String mixinName,
                                          final MethodHandles.Lookup lookup) {
        try {
            method.setAccessible(true);
            return lookup.unreflect(method);
        } catch (final IllegalAccessException e) {
            throw new RuntimeException("Cannot access mixin method: " + mixinName, e);
        }
    }

    // ── Argument utilities ──────────────────────────────────────────────────

    /**
     * Prepends the target object to the argument array so the method handle
     * receives the receiver as the first argument.
     */
    private static Object[] prependTarget(final Object target, final Object[] args) {
        if (args == null || args.length == 0) {
            return new Object[]{target};
        }
        final Object[] allArgs = new Object[args.length + 1];
        allArgs[0] = target;
        System.arraycopy(args, 0, allArgs, 1, args.length);
        return allArgs;
    }

    private static Object firstArgOrNull(final Object[] args) {
        return (args != null && args.length > 0) ? args[0] : null;
    }
}
